### ISSUE TITLE
URL Error- 404 Not Found

### ISSUE THREAD

**Issue by timetoseek** [m-parashar/adblock#4]
First of all, thank you for such a great program!
I noticed today that there was a curl error, please see screen print, below.  Running on Netgear router R8000
![adblock_errors](https://user-images.githubusercontent.com/26972658/106802471-de03bd00-6617-11eb-9dc8-0986aee38c76.jpg)

**Comment by m-parashar** [comment]
My pleasure! And thank you for using it.

These errors are caused by two broken links and do not at all cause any problems except reduced functionality due to missing domains in the broken links. These links are maintained by individuals and organizations other than myself and often go down temporarily or permenently. In case of the latter, I replace the links with alternates or remove the entry altogether.

In this case I have fixed the errors and uploaded a new version. You can update to the new version by using the "-u" option in command line.

**Comment by timetoseek** [comment]
Confirming, all working well now, thank you!

![adblock_working](https://user-images.githubusercontent.com/26972658/106911775-5ff6f300-66b7-11eb-8a99-4412e53cd1eb.jpg)

**Comment by timetoseek** [comment]
I noticed today that there were a few minor errors, possibly the sites are down and these will resolve themselves over time, but just wanted to alert you just in case... please see screen print, below. Running on Netgear router R8000

![adblock_errors](https://user-images.githubusercontent.com/26972658/109550958-cab40800-7a84-11eb-9f32-d469bfd8d320.jpg)
